# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_auto_20170905_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='NO', max_length=120),
        ),
    ]
